FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS base

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install mkdocs

ARG VERSION=0.0.0

WORKDIR /tmp/build

# copy csproj and restore as distinct layers
ENV ASPNETCORE_ENVIRONMENT=Development
COPY ./demo-api/EngineBay.DemoApi/EngineBay.DemoApi.csproj ./demo-api/EngineBay.DemoApi/EngineBay.DemoApi.csproj
RUN dotnet restore ./demo-api/EngineBay.DemoApi/EngineBay.DemoApi.csproj

# copy everything else and build
COPY . .
RUN dotnet publish ./demo-api/EngineBay.DemoApi/EngineBay.DemoApi.csproj --nologo --runtime linux-musl-x64 --self-contained --configuration Release -o /tmp/build/out /p:Version=$VERSION

# build runtime image
FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine
RUN apk add icu-libs
COPY --from=base /tmp/build/out /usr/local/sbin

EXPOSE 5051
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN mkdir /seed-data
ENTRYPOINT ["EngineBay.DemoApi"]